export const dictionaryFilterBar: Record<string, string> = {
  // --- Filters Title ---
  "Filters_af": "Filters", "Filters_ar": "مرشحات", "Filters_az": "Filtrlər", "Filters_bn": "ফিল্টার", "Filters_cs": "Filtry", "Filters_de": "Filter", "Filters_en": "Filters", "Filters_es": "Filtros", "Filters_et": "Filtrid", "Filters_fa": "فیلترها", "Filters_fi": "Suodattimet", "Filters_fr": "Filtres", "Filters_gl": "Filtros", "Filters_gu": "ફિલ્ટર્સ", "Filters_he": "מסננים", "Filters_hi": "फ़िल्टर", "Filters_hr": "Filteri", "Filters_id": "Filter", "Filters_it": "Filtri", "Filters_ja": "フィルター", "Filters_ka": "ფილტრები", "Filters_kk": "Сүзгілер", "Filters_km": "តម្រង", "Filters_ko": "필터", "Filters_lt": "Filtrai", "Filters_lv": "Filtri", "Filters_mk": "Филтри", "Filters_ml": "ഫിൽട്ടറുകൾ", "Filters_mn": "Шүүлтүүр", "Filters_mr": "फिल्टर्स", "Filters_my": "စစ်ထုတ်မှုများ", "Filters_ne": "फिल्टरहरू", "Filters_nl": "Filters", "Filters_pl": "Filtry", "Filters_ps": "فیلټرونه", "Filters_pt": "Filtros", "Filters_ro": "Filtre", "Filters_ru": "Фильтры", "Filters_si": "පෙරහන්", "Filters_sl": "Filtri", "Filters_sv": "Filter", "Filters_sw": "Vichujio", "Filters_ta": "வடிகட்டிகள்", "Filters_te": "వడపోతలు", "Filters_th": "ตัวกรอง", "Filters_tl": "Mga Filter", "Filters_tr": "Filtreler", "Filters_uk": "Фільтри", "Filters_ur": "فلٹرز", "Filters_vi": "Bộ lọc", "Filters_xh": "Izihluzi", "Filters_zh": "筛选",

  // --- Member ---
  "Member_af": "Lid", "Member_ar": "عضو", "Member_az": "Üzv", "Member_bn": "সদস্য", "Member_cs": "Člen", "Member_de": "Mitglied", "Member_en": "Member", "Member_es": "Miembro", "Member_et": "Liige", "Member_fa": "عضو", "Member_fi": "Jäsen", "Member_fr": "Membre", "Member_gl": "Membro", "Member_gu": "સભ્ય", "Member_he": "חבר", "Member_hi": "सदस्य", "Member_hr": "Član", "Member_id": "Anggota", "Member_it": "Membro", "Member_ja": "メンバー", "Member_ka": "წევრი", "Member_kk": "Мүше", "Member_km": "សមាជិក", "Member_ko": "멤버", "Member_lt": "Narys", "Member_lv": "Biedrs", "Member_mk": "Член", "Member_ml": "അംഗം", "Member_mn": "Гишүүн", "Member_mr": "सदस्य", "Member_my": "အဖွဲ့ဝင်", "Member_ne": "सदस्य", "Member_nl": "Lid", "Member_pl": "Członek", "Member_ps": "غړی", "Member_pt": "Membro", "Member_ro": "Membru", "Member_ru": "Участник", "Member_si": "සාමාජිකයා", "Member_sl": "Član", "Member_sv": "Medlem", "Member_sw": "Mwanachama", "Member_ta": "உறுப்பினர்", "Member_te": "సభ్యుడు", "Member_th": "สมาชิก", "Member_tl": "Miyembro", "Member_tr": "Üye", "Member_uk": "Учасник", "Member_ur": "رکن", "Member_vi": "Thành viên", "Member_xh": "Ilungu", "Member_zh": "成员",

  // --- Tags ---
  "Tags_af": "Etikette", "Tags_ar": "وسوم", "Tags_az": "Teqlər", "Tags_bn": "ট্যাগ", "Tags_cs": "Štítky", "Tags_de": "Tags", "Tags_en": "Tags", "Tags_es": "Etiquetas", "Tags_et": "Sildid", "Tags_fa": "برچسب‌ها", "Tags_fi": "Tunnisteet", "Tags_fr": "Étiquettes", "Tags_gl": "Etiquetas", "Tags_gu": "ટેગ્સ", "Tags_he": "תגיות", "Tags_hi": "टैग", "Tags_hr": "Oznake", "Tags_id": "Tag", "Tags_it": "Tag", "Tags_ja": "タグ", "Tags_ka": "ტეგები", "Tags_kk": "Тегтер", "Tags_km": "ស្លាក", "Tags_ko": "태그", "Tags_lt": "Žymos", "Tags_lv": "Tagi", "Tags_mk": "Тагови", "Tags_ml": "ടാഗുകൾ", "Tags_mn": "Пайз", "Tags_mr": "टॅग्स", "Tags_my": "တဂ်များ", "Tags_ne": "ट्यागहरू", "Tags_nl": "Tags", "Tags_pl": "Tagi", "Tags_ps": "ټاګونه", "Tags_pt": "Tags", "Tags_ro": "Etichete", "Tags_ru": "Теги", "Tags_si": "ටැග්", "Tags_sl": "Oznake", "Tags_sv": "Taggar", "Tags_sw": "Lebo", "Tags_ta": "குறிச்சொற்கள்", "Tags_te": "ట్యాగ్‌లు", "Tags_th": "แท็ก", "Tags_tl": "Mga Tag", "Tags_tr": "Etiketler", "Tags_uk": "Теги", "Tags_ur": "ٹیگز", "Tags_vi": "Thẻ", "Tags_xh": "Iithegi", "Tags_zh": "标签",

  // --- Sprint ---
  "Sprint_af": "Naelloop", "Sprint_ar": "سبرينت", "Sprint_az": "Sprint", "Sprint_bn": "স্প্রিন্ট", "Sprint_cs": "Sprint", "Sprint_de": "Sprint", "Sprint_en": "Sprint", "Sprint_es": "Sprint", "Sprint_et": "Sprint", "Sprint_fa": "اسپرینت", "Sprint_fi": "Sprintti", "Sprint_fr": "Sprint", "Sprint_gl": "Sprint", "Sprint_gu": "સ્પ્રિન્ટ", "Sprint_he": "ספרינט", "Sprint_hi": "स्प्रिंट", "Sprint_hr": "Sprint", "Sprint_id": "Sprint", "Sprint_it": "Sprint", "Sprint_ja": "スプリント", "Sprint_ka": "სპრინტი", "Sprint_kk": "Спринт", "Sprint_km": "ស្ព្រីន", "Sprint_ko": "스프린트", "Sprint_lt": "Sprintas", "Sprint_lv": "Sprints", "Sprint_mk": "Спринт", "Sprint_ml": "സ്പ്രിന്റ്", "Sprint_mn": "Спринт", "Sprint_mr": "स्प्रिंट", "Sprint_my": "စပရင့်", "Sprint_ne": "स्प्रिन्ट", "Sprint_nl": "Sprint", "Sprint_pl": "Sprint", "Sprint_ps": "سپرینټ", "Sprint_pt": "Sprint", "Sprint_ro": "Sprint", "Sprint_ru": "Спринт", "Sprint_si": "ස්ප්‍රින්ට්", "Sprint_sl": "Sprint", "Sprint_sv": "Sprint", "Sprint_sw": "Sprinti", "Sprint_ta": "ஸ்பிரிண்ட்", "Sprint_te": "స్ప్రింట్", "Sprint_th": "สปรินต์", "Sprint_tl": "Sprint", "Sprint_tr": "Sprint", "Sprint_uk": "Спринт", "Sprint_ur": "اسپرنٹ", "Sprint_vi": "Sprint", "Sprint_xh": "Isprinti", "Sprint_zh": "冲刺"
};

export const getFilterBarTranslation = (key: string, lang: string): string => {
  const lookupKey = `${key}_${lang}`;
  return dictionaryFilterBar[lookupKey] || dictionaryFilterBar[`${key}_en`] || key;
};