// utils/dictionary_task_summary.ts
export type Dictionary = Record<string, string>;

export const dictionaryTaskSummary: Dictionary = {
  // --- Titles ---
  "Projects_af": "Projekte", "Projects_ar": "المشاريع", "Projects_az": "Layihələr", "Projects_bn": "প্রকল্প", "Projects_cs": "Projekty", "Projects_de": "Projekte", "Projects_en": "Projects", "Projects_es": "Proyectos", "Projects_et": "Projektid", "Projects_fa": "پروژه‌ها", "Projects_fi": "Projektit", "Projects_fr": "Projets", "Projects_gl": "Proxectos", "Projects_gu": "પ્રોજેક્ટ્સ", "Projects_he": "פרויקטים", "Projects_hi": "परियोजनाएं", "Projects_hr": "Projekti", "Projects_id": "Proyek", "Projects_it": "Progetti", "Projects_ja": "プロジェクト", "Projects_ka": "პროექტები", "Projects_kk": "Жобалар", "Projects_km": "គម្រោង", "Projects_ko": "프로젝트", "Projects_lt": "Projektai", "Projects_lv": "Projekti", "Projects_mk": "Проекти", "Projects_ml": "പ്രോജക്റ്റുകൾ", "Projects_mn": "Төслүүд", "Projects_mr": "प्रकल्प", "Projects_my": "စီမံကိန်းများ", "Projects_ne": "आयोजनाहरू", "Projects_nl": "Projecten", "Projects_pl": "Projekty", "Projects_ps": "پروژې", "Projects_pt": "Projetos", "Projects_ro": "Proiecte", "Projects_ru": "Проекты", "Projects_si": "ව්‍යාපෘති", "Projects_sl": "Projekti", "Projects_sv": "Projekt", "Projects_sw": "Miradi", "Projects_ta": "திட்டங்கள்", "Projects_te": "ప్రాజెక్టులు", "Projects_th": "โครงการ", "Projects_tl": "Mga Proyekto", "Projects_tr": "Projeler", "Projects_uk": "Проєкти", "Projects_ur": "منصوبے", "Projects_vi": "Dự án", "Projects_xh": "Iiprojekthi", "Projects_zh": "项目",

  // --- Create Project ---
  "Create Project_af": "Skep Projek", "Create Project_ar": "إنشاء مشروع", "Create Project_az": "Layihə yarat", "Create Project_bn": "প্রকল্প তৈরি করুন", "Create Project_cs": "Vytvořit projekt", "Create Project_de": "Projekt erstellen", "Create Project_en": "Create Project", "Create Project_es": "Crear proyecto", "Create Project_et": "Loo projekt", "Create Project_fa": "ایجاد پروژه", "Create Project_fi": "Luo projekti", "Create Project_fr": "Créer un projet", "Create Project_gl": "Crear proxecto", "Create Project_gu": "પ્રોજેક્ટ બનાવો", "Create Project_he": "יצירת פרויקט", "Create Project_hi": "परियोजना बनाएँ", "Create Project_hr": "Kreiraj projekt", "Create Project_id": "Buat Proyek", "Create Project_it": "Crea progetto", "Create Project_ja": "プロジェクトを作成", "Create Project_ka": "პროექტის შექმნა", "Create Project_kk": "Жоба құру", "Create Project_km": "បង្កើតគម្រោង", "Create Project_ko": "프로젝트 생성", "Create Project_lt": "Sukurti projektą", "Create Project_lv": "Izveidot projektu", "Create Project_mk": "Креирај проект", "Create Project_ml": "പ്രോജക്റ്റ് സൃഷ്ടിക്കുക", "Create Project_mn": "Төсөл үүсгэх", "Create Project_mr": "प्रकल्प तयार करा", "Create Project_my": "စီမံကိန်းအသစ်ဖန်တီးရန်", "Create Project_ne": "आयोजना सिर्जना गर्नुहोस्", "Create Project_nl": "Project maken", "Create Project_pl": "Utwórz projekt", "Create Project_ps": "پروژه جوړول", "Create Project_pt": "Criar Projeto", "Create Project_ro": "Creare proiect", "Create Project_ru": "Создать проект", "Create Project_si": "ව්‍යාපෘතියක් සාදන්න", "Create Project_sl": "Ustvari projekt", "Create Project_sv": "Skapa projekt", "Create Project_sw": "Unda Mradi", "Create Project_ta": "திட்டத்தை உருவாக்கு", "Create Project_te": "ప్రాజెక్ట్‌ను సృష్టించండి", "Create Project_th": "สร้างโครงการ", "Create Project_tl": "Gumawa ng Proyekto", "Create Project_tr": "Proje Oluştur", "Create Project_uk": "Створити проєкт", "Create Project_ur": "منصوبہ بنائیں", "Create Project_vi": "Tạo dự án", "Create Project_xh": "Yenza iiprojekthi", "Create Project_zh": "创建项目",

  // --- Edit Project ---
  "Edit Project_af": "Wysig Projek", "Edit Project_ar": "تعديل المشروع", "Edit Project_az": "Layihəni redaktə et", "Edit Project_bn": "প্রকল্প সম্পাদনা করুন", "Edit Project_cs": "Upravit projekt", "Edit Project_de": "Projekt bearbeiten", "Edit Project_en": "Edit Project", "Edit Project_es": "Editar proyecto", "Edit Project_et": "Muuda projekti", "Edit Project_fa": "ویرایش پروژه", "Edit Project_fi": "Muokkaa projektia", "Edit Project_fr": "Modifier le projet", "Edit Project_gl": "Editar proxecto", "Edit Project_gu": "પ્રોજેક્ટ સંપાદિત કરો", "Edit Project_he": "עריכת פרויקט", "Edit Project_hi": "परियोजना संपादित करें", "Edit Project_hr": "Uredi projekt", "Edit Project_id": "Edit Proyek", "Edit Project_it": "Modifica progetto", "Edit Project_ja": "プロジェクトを編集", "Edit Project_ka": "პროექტის რედაქტირება", "Edit Project_kk": "Жобаны өңдеу", "Edit Project_km": "កែសម្រួលគម្រោង", "Edit Project_ko": "프로젝트 편집", "Edit Project_lt": "Redaguoti projektą", "Edit Project_lv": "Rediģēt projektu", "Edit Project_mk": "Уреди проект", "Edit Project_ml": "പ്രോജക്റ്റ് എഡിറ്റ് ചെയ്യുക", "Edit Project_mn": "Төсөл засах", "Edit Project_mr": "प्रकल्प संपादित करा", "Edit Project_my": "စီမံကိန်းကို ပြင်ဆင်ရန်", "Edit Project_ne": "आयोजना सम्पादन गर्नुहोस्", "Edit Project_nl": "Project bewerken", "Edit Project_pl": "Edytuj projekt", "Edit Project_ps": "پروژه سمول", "Edit Project_pt": "Editar Projeto", "Edit Project_ro": "Editare proiect", "Edit Project_ru": "Редактировать проект", "Edit Project_si": "ව්‍යාපෘතිය සංස්කරණය කරන්න", "Edit Project_sl": "Uredi projekt", "Edit Project_sv": "Redigera projekt", "Edit Project_sw": "Hariri Mradi", "Edit Project_ta": "திட்டத்தைத் திருத்து", "Edit Project_te": "ప్రాజెక్ట్‌ను సవరించండి", "Edit Project_th": "แก้ไขโครงการ", "Edit Project_tl": "I-edit ang Proyekto", "Edit Project_tr": "Projeyi Düzenle", "Edit Project_uk": "Редагувати проєкт", "Edit Project_ur": "منصوبہ ترمیم کریں", "Edit Project_vi": "Chỉnh sửa dự án", "Edit Project_xh": "Hlela iiprojekthi", "Edit Project_zh": "编辑项目",

  // --- tasks label ---
  "tasks_af": "take", "tasks_ar": "مهام", "tasks_az": "tapşırıqlar", "tasks_bn": "কাজ", "tasks_cs": "úkoly", "tasks_de": "Aufgaben", "tasks_en": "tasks", "tasks_es": "tareas", "tasks_et": "ülesannet", "tasks_fa": "وظایف", "tasks_fi": "tehtävää", "tasks_fr": "tâches", "tasks_gl": "tarefas", "tasks_gu": "કાર્યો", "tasks_he": "משימות", "tasks_hi": "कार्य", "tasks_hr": "zadaci", "tasks_id": "tugas", "tasks_it": "attività", "tasks_ja": "タスク", "tasks_ka": "დავალებები", "tasks_kk": "тапсырмалар", "tasks_km": "ភារកិច្ច", "tasks_ko": "작업", "tasks_lt": "užduotys", "tasks_lv": "uzdevumi", "tasks_mk": "задачи", "tasks_ml": "ചുമതലകൾ", "tasks_mn": "даалгавар", "tasks_mr": "कामे", "tasks_my": "အလုပ်များ", "tasks_ne": "कार्यहरू", "tasks_nl": "taken", "tasks_pl": "zadania", "tasks_ps": "دندې", "tasks_pt": "tarefas", "tasks_ro": "sarcini", "tasks_ru": "задач", "tasks_si": "කාර්යයන්", "tasks_sl": "naloge", "tasks_sv": "uppgifter", "tasks_sw": "majukumu", "tasks_ta": "பணிகள்", "tasks_te": "పనులు", "tasks_th": "งาน", "tasks_tl": "mga gawain", "tasks_tr": "görev", "tasks_uk": "завдань", "tasks_ur": "ٹاسک", "tasks_vi": "nhiệm vụ", "tasks_xh": "imisebenzi", "tasks_zh": "任务",

  // --- in progress label ---
  "in progress_af": "besig", "in progress_ar": "قيد التنفيذ", "in progress_az": "icra edilir", "in progress_bn": "চলমান", "in progress_cs": "probíhá", "in progress_de": "in Bearbeitung", "in progress_en": "in progress", "in progress_es": "en progreso", "in progress_et": "teoksil", "in progress_fa": "در حال انجام", "in progress_fi": "kesken", "in progress_fr": "en cours", "in progress_gl": "en curso", "in progress_gu": "પ્રગતિમાં છે", "in progress_he": "בתהליך", "in progress_hi": "प्रगति में", "in progress_hr": "u tijeku", "in progress_id": "sedang berjalan", "in progress_it": "in corso", "in progress_ja": "進行中", "in progress_ka": "მიმდინარე", "in progress_kk": "орындалуда", "in progress_km": "កំពុងដំណើរការ", "in progress_ko": "진행 중", "in progress_lt": "vykdoma", "in progress_lv": "procesā", "in progress_mk": "во тек", "in progress_ml": "പുരോഗമിക്കുന്നു", "in progress_mn": "хийгдэж байна", "in progress_mr": "प्रगतीपथावर", "in progress_my": "လုပ်ဆောင်နေဆဲ", "in progress_ne": "प्रगतिमा", "in progress_nl": "in behandeling", "in progress_pl": "w toku", "in progress_ps": "په کار کې", "in progress_pt": "em andamento", "in progress_ro": "în curs", "in progress_ru": "в работе", "in progress_si": "සිදුවෙමින් පවතී", "in progress_sl": "v teku", "in progress_sv": "pågår", "in progress_sw": "inaendelea", "in progress_ta": "செயலில் உள்ளது", "in progress_te": "ప్రగతిలో ఉంది", "in progress_th": "กำลังดำเนินการ", "in progress_tl": "kasalukuyang ginagawa", "in progress_tr": "devam ediyor", "in progress_uk": "у процесі", "in progress_ur": "جاری ہے", "in progress_vi": "đang thực hiện", "in progress_xh": "iyaqhuba", "in progress_zh": "进行中",

  // --- members label ---
  "members_af": "lede", "members_ar": "أعضاء", "members_az": "üzvlər", "members_bn": "সদস্য", "members_cs": "členové", "members_de": "Mitglieder", "members_en": "members", "members_es": "miembros", "members_et": "liiget", "members_fa": "اعضا", "members_fi": "jäsentä", "members_fr": "membres", "members_gl": "membros", "members_gu": "સભ્યો", "members_he": "חברים", "members_hi": "सदस्य", "members_hr": "članovi", "members_id": "anggota", "members_it": "membri", "members_ja": "メンバー", "members_ka": "წევრები", "members_kk": "мүшелер", "members_km": "សមាជិក", "members_ko": "멤버", "members_lt": "nariai", "members_lv": "dalībnieki", "members_mk": "членови", "members_ml": "അംഗങ്ങൾ", "members_mn": "гишүүд", "members_mr": "सदस्य", "members_my": "အဖွဲ့ဝင်များ", "members_ne": "सदस्यहरू", "members_nl": "leden", "members_pl": "członkowie", "members_ps": "غړي", "members_pt": "membros", "members_ro": "membri", "members_ru": "участников", "members_si": "සාමාජිකයන්", "members_sl": "člani", "members_sv": "medlemmar", "members_sw": "wanachama", "members_ta": "உறுப்பினர்கள்", "members_te": "సభ్యులు", "members_th": "สมาชิก", "members_tl": "mga miyembro", "members_tr": "üye", "members_uk": "учасників", "members_ur": "ارکان", "members_vi": "thành viên", "members_xh": "amalungu", "members_zh": "成员",

  // --- No projects found label ---
  "No projects found._af": "Geen projekte gevind nie.", "No projects found._ar": "لم يتم العثور على مشاريع.", "No projects found._az": "Heç bir layihə tapılmadı.", "No projects found._bn": "কোন প্রকল্প পাওয়া যায়নি।", "No projects found._cs": "Nebyly nalezeny žádné projekty.", "No projects found._de": "Keine Projekte gefunden.", "No projects found._en": "No projects found.", "No projects found._es": "No se encontraron proyectos.", "No projects found._et": "Projekte ei leitud.", "No projects found._fa": "پروژه‌ای یافت نشد.", "No projects found._fi": "Projekteja ei löytynyt.", "No projects found._fr": "Aucun projet trouvé.", "No projects found._gl": "Non se atoparon proxectos.", "No projects found._gu": "કોઈ પ્રોજેક્ટ મળ્યા નથી.", "No projects found._he": "לא נמצאו פרויקטים.", "No projects found._hi": "कोई परियोजना नहीं मिली।", "No projects found._hr": "Nisu pronađeni projekti.", "No projects found._id": "Proyek tidak ditemukan.", "No projects found._it": "Nessun progetto trovato.", "No projects found._ja": "プロジェクトが見つかりません。", "No projects found._ka": "პროექტები ვერ მოიძებნა.", "No projects found._kk": "Жобалар табылмады.", "No projects found._km": "រកមិនឃើញគម្រោងទេ។", "No projects found._ko": "프로젝트를 찾을 수 없습니다.", "No projects found._lt": "Projektų nerasta.", "No projects found._lv": "Projekti netika atrasti.", "No projects found._mk": "Не се пронајдени проекти.", "No projects found._ml": "പ്രോജക്റ്റുകളൊന്നും കണ്ടെത്താനായില്ല.", "No projects found._mn": "Төсөл олдсонгүй.", "No projects found._mr": "कोणतेही प्रकल्प आढळले नाहीत.", "No projects found._my": "မည်သည့်စီမံကိန်းမှ မတွေ့ပါ။", "No projects found._ne": "कुनै आयोजना फेला परेन।", "No projects found._nl": "Geen projecten gevonden.", "No projects found._pl": "Nie znaleziono żadnych projektů.", "No projects found._ps": "هیڅ پروژه ونه موندل شوه.", "No projects found._pt": "Nenhum projeto encontrado.", "No projects found._ro": "Nu s-au găsit proiecte.", "No projects found._ru": "Проекты не найдены.", "No projects found._si": "ව්‍යාපෘති කිසිවක් හමු නොවීය.", "No projects found._sl": "Projektov ni bilo mogoče najti.", "No projects found._sv": "Inga projekt hittades.", "No projects found._sw": "Hakuna miradi iliyopatikana.", "No projects found._ta": "திட்டங்கள் எதுவும் கிடைக்கவில்லை.", "No projects found._te": "ప్రాజెక్ట్‌లు ఏవీ కనుగొనబడలేదు.", "No projects found._th": "ไม่พบโครงการ", "No projects found._tl": "Walang nakitang proyekto.", "No projects found._tr": "Proje bulunamadı.", "No projects found._uk": "Проєктів не знайдено.", "No projects found._ur": "کوئی منصوبہ نہیں ملا۔", "No projects found._vi": "Không tìm thấy dự án nào.", "No projects found._xh": "Akukho iiprojekthi zifunyenweyo.", "No projects found._zh": "未找到项目。",
};

export const getTaskSummaryTranslation = (key: string, lang: string): string => {
  const lookupKey = `${key}_${lang}`;
  return dictionaryTaskSummary[lookupKey] || dictionaryTaskSummary[`${key}_en`] || key;
};