// utils/dictionary_sidebar.ts

export type Dictionary = Record<string, string>;

export const dictionarySidebar: Dictionary = {
  // --- Roles: Manager ---
  "Manager_af": "Bestuurder", "Manager_ar": "مدير", "Manager_az": "Menecer", "Manager_bn": "ব্যবস্থাপক", "Manager_cs": "Manažer", "Manager_de": "Manager", "Manager_en": "Manager", "Manager_es": "Gerente", "Manager_et": "Haldur", "Manager_fa": "مدیر", "Manager_fi": "Päällikkö", "Manager_fr": "Gestionnaire", "Manager_gl": "Xerente", "Manager_gu": "મેનેજર", "Manager_he": "מנהל", "Manager_hi": "प्रबंधक", "Manager_hr": "Voditelj", "Manager_id": "Manajer", "Manager_it": "Gestore", "Manager_ja": "マネージャー", "Manager_ka": "მენეჯერი", "Manager_kk": "Менеджер", "Manager_km": "អ្នកគ្រប់គ្រង", "Manager_ko": "관리자", "Manager_lt": "Vadovas", "Manager_lv": "Vadītājs", "Manager_mk": "Менаџер", "Manager_ml": "മാനേജർ", "Manager_mn": "Менежер", "Manager_mr": "व्यवस्थापक", "Manager_my": "မန်နေဂျာ", "Manager_ne": "प्रबन्धक", "Manager_nl": "Manager", "Manager_pl": "Menedżer", "Manager_ps": "مدیر", "Manager_pt": "Gerente", "Manager_ro": "Manager", "Manager_ru": "Менеджер", "Manager_si": "කළමනාකරු", "Manager_sl": "Vodja", "Manager_sv": "Chef", "Manager_sw": "Meneja", "Manager_ta": "மேலாளர்", "Manager_te": "మేనేజర్", "Manager_th": "ผู้จัดการ", "Manager_tl": "Tagapamahala", "Manager_tr": "Yönetici", "Manager_uk": "Менеджер", "Manager_ur": "مینیجر", "Manager_vi": "Quản lý", "Manager_xh": "Imenjala", "Manager_zh": "经理",

  // --- Roles: Member ---
  "Member_af": "Lid", "Member_ar": "عضو", "Member_az": "Üzv", "Member_bn": "সদস্য", "Member_cs": "Člen", "Member_de": "Mitglied", "Member_en": "Member", "Member_es": "Miembro", "Member_et": "Liige", "Member_fa": "عضو", "Member_fi": "Jäsen", "Member_fr": "Membre", "Member_gl": "Membro", "Member_gu": "સભ્ય", "Member_he": "חבר", "Member_hi": "सदस्य", "Member_hr": "Član", "Member_id": "Anggota", "Member_it": "Membro", "Member_ja": "メンバー", "Member_ka": "წევრი", "Member_kk": "Мүше", "Member_km": "សមាជិក", "Member_ko": "회원", "Member_lt": "Narys", "Member_lv": "Biedrs", "Member_mk": "Член", "Member_ml": "അംഗം", "Member_mn": "Гишүүн", "Member_mr": "सदस्य", "Member_my": "အဖွဲ့ဝင်", "Member_ne": "सदस्य", "Member_nl": "Lid", "Member_pl": "Członek", "Member_ps": "غړی", "Member_pt": "Membro", "Member_ro": "Membru", "Member_ru": "Участник", "Member_si": "සාමාජිකයා", "Member_sl": "Član", "Member_sv": "Medlem", "Member_sw": "Mwanachama", "Member_ta": "உறுப்பினர்", "Member_te": "సభ్యుడు", "Member_th": "สมาชิก", "Member_tl": "Kasapi", "Member_tr": "Üye", "Member_uk": "Учасник", "Member_ur": "رکن", "Member_vi": "Thành viên", "Member_xh": "Ilungu", "Member_zh": "成员",

  // --- Sections: MAIN ---
  "MAIN_af": "HOOF", "MAIN_ar": "الرئيسية", "MAIN_az": "ƏSAS", "MAIN_bn": "প্রধান", "MAIN_cs": "HLAVNÍ", "MAIN_de": "HAUPTMENÜ", "MAIN_en": "MAIN", "MAIN_es": "PRINCIPAL", "MAIN_et": "PÕHILINE", "MAIN_fa": "اصلی", "MAIN_fi": "PÄÄVALIKKO", "MAIN_fr": "PRINCIPAL", "MAIN_gl": "PRINCIPAL", "MAIN_gu": "મુખ્ય", "MAIN_he": "ראשי", "MAIN_hi": "मुख्य", "MAIN_hr": "GLAVNO", "MAIN_id": "UTAMA", "MAIN_it": "PRINCIPALE", "MAIN_ja": "メイン", "MAIN_ka": "მთავარი", "MAIN_kk": "НЕГІЗГІ", "MAIN_km": "មេ", "MAIN_ko": "메인", "MAIN_lt": "PAGRINDINIS", "MAIN_lv": "GALVENAIS", "MAIN_mk": "ГЛАВНО", "MAIN_ml": "പ്രധാന", "MAIN_mn": "ҮНДСЭН", "MAIN_mr": "मुख्य", "MAIN_my": "ပင်မ", "MAIN_ne": "मुख्य", "MAIN_nl": "HOOFD", "MAIN_pl": "GŁÓWNE", "MAIN_ps": "اصلي", "MAIN_pt": "PRINCIPAL", "MAIN_ro": "PRINCIPAL", "MAIN_ru": "ГЛАВНОЕ", "MAIN_si": "ප්‍රධාන", "MAIN_sl": "GLAVNO", "MAIN_sv": "HUVUDMENY", "MAIN_sw": "KUU", "MAIN_ta": "முதன்மை", "MAIN_te": "ప్రధాన", "MAIN_th": "หลัก", "MAIN_tl": "PANGUNAHIN", "MAIN_tr": "ANA", "MAIN_uk": "ГОЛОВНЕ", "MAIN_ur": "مرکزی", "MAIN_vi": "CHÍNH", "MAIN_xh": "EINGUNDO", "MAIN_zh": "主菜单",

  // --- Sections: SETTINGS ---
  "SETTINGS_SECTION_af": "INSTELLINGS", "SETTINGS_SECTION_ar": "الإعدادات", "SETTINGS_SECTION_az": "AYARLAR", "SETTINGS_SECTION_bn": "সেটিংস", "SETTINGS_SECTION_cs": "NASTAVENÍ", "SETTINGS_SECTION_de": "EINSTELLUNGEN", "SETTINGS_SECTION_en": "SETTINGS", "SETTINGS_SECTION_es": "AJUSTES", "SETTINGS_SECTION_et": "SEADED", "SETTINGS_SECTION_fa": "تنظیمات", "SETTINGS_SECTION_fi": "ASETUKSET", "SETTINGS_SECTION_fr": "PARAMÈTRES", "SETTINGS_SECTION_gl": "AXUSTES", "SETTINGS_SECTION_gu": "સેટિંગ્સ", "SETTINGS_SECTION_he": "הגדרות", "SETTINGS_SECTION_hi": "सेटिंग्स", "SETTINGS_SECTION_hr": "POSTAVKE", "SETTINGS_SECTION_id": "PENGATURAN", "SETTINGS_SECTION_it": "IMPOSTAZIONI", "SETTINGS_SECTION_ja": "設定", "SETTINGS_SECTION_ka": "პარამეტრები", "SETTINGS_SECTION_kk": "ПАРАМЕТРЛЕР", "SETTINGS_SECTION_km": "ការកំណត់", "SETTINGS_SECTION_ko": "설정", "SETTINGS_SECTION_lt": "NUSTATYMAI", "SETTINGS_SECTION_lv": "IESTATĪJUMI", "SETTINGS_SECTION_mk": "ПОСТАВКИ", "SETTINGS_SECTION_ml": "ക്രമീകരണങ്ങൾ", "SETTINGS_SECTION_mn": "ТОХИРГОО", "SETTINGS_SECTION_mr": "सेटिंग्स", "SETTINGS_SECTION_my": "ဆက်တင်များ", "SETTINGS_SECTION_ne": "सेटिङ्हरू", "SETTINGS_SECTION_nl": "INSTELLINGEN", "SETTINGS_SECTION_pl": "USTAWIENIA", "SETTINGS_SECTION_ps": "ترتیبات", "SETTINGS_SECTION_pt": "CONFIGURAÇÕES", "SETTINGS_SECTION_ro": "SETĂRI", "SETTINGS_SECTION_ru": "НАСТРОЙКИ", "SETTINGS_SECTION_si": "සැකසුම්", "SETTINGS_SECTION_sl": "NASTAVITVE", "SETTINGS_SECTION_sv": "INSTÄLLNINGAR", "SETTINGS_SECTION_sw": "MIPANGILIO", "SETTINGS_SECTION_ta": "அமைப்புகள்", "SETTINGS_SECTION_te": "సెట్టింగులు", "SETTINGS_SECTION_th": "การตั้งค่า", "SETTINGS_SECTION_tl": "MGA SETTING", "SETTINGS_SECTION_tr": "AYARLAR", "SETTINGS_SECTION_uk": "НАЛАШТУВАННЯ", "SETTINGS_SECTION_ur": "ترتیبات", "SETTINGS_SECTION_vi": "CÀI ĐẶT", "SETTINGS_SECTION_xh": "IZILWANDE", "SETTINGS_SECTION_zh": "设置",

  // --- Nav: Dashboard ---
  "Dashboard_af": "Instrumentepaneel", "Dashboard_ar": "لوحة القيادة", "Dashboard_az": "İdarə paneli", "Dashboard_bn": "ড্যাশবোর্ড", "Dashboard_cs": "Nástěnka", "Dashboard_de": "Dashboard", "Dashboard_en": "Dashboard", "Dashboard_es": "Tablero", "Dashboard_et": "Töölaud", "Dashboard_fa": "داشبورد", "Dashboard_fi": "Ohjauspaneeli", "Dashboard_fr": "Tableau de bord", "Dashboard_gl": "Taboleiro", "Dashboard_gu": "ડેશબોર્ડ", "Dashboard_he": "לוח בקרה", "Dashboard_hi": "डैशबोर्ड", "Dashboard_hr": "Nadzorna ploča", "Dashboard_id": "Dasbor", "Dashboard_it": "Bacheca", "Dashboard_ja": "ダッシュボード", "Dashboard_ka": "პანელი", "Dashboard_kk": "Бақылау тақтасы", "Dashboard_km": "ផ្ទាំងគ្រប់គ្រង", "Dashboard_ko": "대시보드", "Dashboard_lt": "Skydelis", "Dashboard_lv": "Informācijas panelis", "Dashboard_mk": "Контролна табла", "Dashboard_ml": "ഡാഷ്ബോർഡ്", "Dashboard_mn": "Хяналтын самбар", "Dashboard_mr": "डॅशबोर्ड", "Dashboard_my": "ဒိုင်ခွက်", "Dashboard_ne": "ड्यासबোর্ড", "Dashboard_nl": "Dashboard", "Dashboard_pl": "Panel", "Dashboard_ps": "ډشبورډ", "Dashboard_pt": "Painel", "Dashboard_ro": "Tablou de bord", "Dashboard_ru": "Панель", "Dashboard_si": "උපකරණ පුවරුව", "Dashboard_sl": "Nadzorna plošča", "Dashboard_sv": "Översikt", "Dashboard_sw": "Dashibodi", "Dashboard_ta": "டாஷ்போர்டு", "Dashboard_te": "డ్యాష్‌బోర్డ్", "Dashboard_th": "แผงควบคุม", "Dashboard_tl": "Dashboard", "Dashboard_tr": "Panel", "Dashboard_uk": "Панель", "Dashboard_ur": "ڈیش بورڈ", "Dashboard_vi": "Bảng điều khiển", "Dashboard_xh": "Idatshibodi", "Dashboard_zh": "仪表板",

  // --- Nav: Projects ---
  "Projects_af": "Projekte", "Projects_ar": "المشاريع", "Projects_az": "Layihələr", "Projects_bn": "প্রকল্প", "Projects_cs": "Projekty", "Projects_de": "Projekte", "Projects_en": "Projects", "Projects_es": "Proyectos", "Projects_et": "Projektid", "Projects_fa": "پروژه‌ها", "Projects_fi": "Projektit", "Projects_fr": "Projets", "Projects_gl": "Proxectos", "Projects_gu": "પ્રોજેક્ટ્સ", "Projects_he": "פרויקטים", "Projects_hi": "परियोजनाएं", "Projects_hr": "Projekti", "Projects_id": "Proyek", "Projects_it": "Progetti", "Projects_ja": "プロジェクト", "Projects_ka": "პროექტები", "Projects_kk": "Жобалар", "Projects_km": "គម្រោង", "Projects_ko": "프로젝트", "Projects_lt": "Projektai", "Projects_lv": "Projekti", "Projects_mk": "Проекти", "Projects_ml": "പ്രോജക്റ്റുകൾ", "Projects_mn": "Төслүүд", "Projects_mr": "प्रकल्प", "Projects_my": "စီမံကိန်းများ", "Projects_ne": "आयोजनाहरू", "Projects_nl": "Projecten", "Projects_pl": "Projekty", "Projects_ps": "پروژې", "Projects_pt": "Projetos", "Projects_ro": "Proiecte", "Projects_ru": "Проекты", "Projects_si": "ව්‍යාපෘති", "Projects_sl": "Projekti", "Projects_sv": "Projekt", "Projects_sw": "Miradi", "Projects_ta": "திட்டங்கள்", "Projects_te": "ప్రాజెక్టులు", "Projects_th": "โครงการ", "Projects_tl": "Mga Proyekto", "Projects_tr": "Projeler", "Projects_uk": "Проєкти", "Projects_ur": "منصوبے", "Projects_vi": "Dự án", "Projects_xh": "Iiprojekthi", "Projects_zh": "项目",

  // --- Nav: Tags ---
  "Tags_af": "Etikette", "Tags_ar": "العلامات", "Tags_az": "Teqlər", "Tags_bn": "ট্যাগ", "Tags_cs": "Štítky", "Tags_de": "Tags", "Tags_en": "Tags", "Tags_es": "Etiquetas", "Tags_et": "Sildid", "Tags_fa": "برچسب‌ها", "Tags_fi": "Tunnisteet", "Tags_fr": "Étiquettes", "Tags_gl": "Etiquetas", "Tags_gu": "ટેગ્સ", "Tags_he": "תגיות", "Tags_hi": "टैग", "Tags_hr": "Oznake", "Tags_id": "Tag", "Tags_it": "Tag", "Tags_ja": "タグ", "Tags_ka": "ტეგები", "Tags_kk": "Тегтер", "Tags_km": "ស្លាក", "Tags_ko": "태그", "Tags_lt": "Žymos", "Tags_lv": "Birkas", "Tags_mk": "Тагови", "Tags_ml": "ടാഗുകൾ", "Tags_mn": "Шошго", "Tags_mr": "टॅग", "Tags_my": "တက်ဂ်များ", "Tags_ne": "ट्यागहरू", "Tags_nl": "Tags", "Tags_pl": "Tagi", "Tags_ps": "ټاګونه", "Tags_pt": "Etiquetas", "Tags_ro": "Etichete", "Tags_ru": "Теги", "Tags_si": "ටැග්", "Tags_sl": "Oznake", "Tags_sv": "Taggar", "Tags_sw": "Lebo", "Tags_ta": "குறிச்சொற்கள்", "Tags_te": "ట్యాగ్‌లు", "Tags_th": "แท็ก", "Tags_tl": "Mga Tag", "Tags_tr": "Etiketler", "Tags_uk": "Теги", "Tags_ur": "ٹیگز", "Tags_vi": "Thẻ", "Tags_xh": "Iithegi", "Tags_zh": "标签",

  // --- Nav: Sprints ---
  "Sprints_af": "Naellope", "Sprints_ar": "سبرينت", "Sprints_az": "Sprintlər", "Sprints_bn": "স্প্রিন্ট", "Sprints_cs": "Sprinty", "Sprints_de": "Sprints", "Sprints_en": "Sprints", "Sprints_es": "Sprints", "Sprints_et": "Sprindid", "Sprints_fa": "اسپرینت‌ها", "Sprints_fi": "Sprintit", "Sprints_fr": "Sprints", "Sprints_gl": "Sprints", "Sprints_gu": "સ્પ્રિન્ટ્સ", "Sprints_he": "ספרינטים", "Sprints_hi": "स्प्रिंट", "Sprints_hr": "Sprintovi", "Sprints_id": "Sprint", "Sprints_it": "Sprint", "Sprints_ja": "スプリント", "Sprints_ka": "სპრინტები", "Sprints_kk": "Спринттер", "Sprints_km": "ស្ព្រីន", "Sprints_ko": "스프린트", "Sprints_lt": "Sprintai", "Sprints_lv": "Sprinti", "Sprints_mk": "Спринтови", "Sprints_ml": "സ്പ്രിന്റുകൾ", "Sprints_mn": "Спринтүүд", "Sprints_mr": "स्प्रिंट", "Sprints_my": "စပရင့်များ", "Sprints_ne": "स्प्रिन्टहरू", "Sprints_nl": "Sprints", "Sprints_pl": "Sprinty", "Sprints_ps": "سپرینټونه", "Sprints_pt": "Sprints", "Sprints_ro": "Sprinturi", "Sprints_ru": "Спринты", "Sprints_si": "ස්ප්‍රින්ට්", "Sprints_sl": "Sprinti", "Sprints_sv": "Sprintar", "Sprints_sw": "Sprints", "Sprints_ta": "ஸ்பிரிண்ட்கள்", "Sprints_te": "స్ప్రింట్లు", "Sprints_th": "สปรินต์", "Sprints_tl": "Sprints", "Sprints_tr": "Sprintler", "Sprints_uk": "Спринти", "Sprints_ur": "اسپرنٹ", "Sprints_vi": "Sprint", "Sprints_xh": "Ii-sprint", "Sprints_zh": "冲刺",

  // --- Nav: Settings ---
  "Settings_af": "Instellings", "Settings_ar": "الإعدادات", "Settings_az": "Ayarlar", "Settings_bn": "সেটিংস", "Settings_cs": "Nastavení", "Settings_de": "Einstellungen", "Settings_en": "Settings", "Settings_es": "Configuración", "Settings_et": "Seaded", "Settings_fa": "تنظیمات", "Settings_fi": "Asetukset", "Settings_fr": "Paramètres", "Settings_gl": "Axustes", "Settings_gu": "સેટિંગ્સ", "Settings_he": "הגדרות", "Settings_hi": "सेटिंग्स", "Settings_hr": "Postavke", "Settings_id": "Pengaturan", "Settings_it": "Impostazioni", "Settings_ja": "設定", "Settings_ka": "პარამეტრები", "Settings_kk": "Параметрлер", "Settings_km": "ការកំណត់", "Settings_ko": "설정", "Settings_lt": "Nustatymai", "Settings_lv": "Iestatījumi", "Settings_mk": "Поставки", "Settings_ml": "ക്രമീകരണങ്ങൾ", "Settings_mn": "Тохиргоо", "Settings_mr": "सेटिंग्स", "Settings_my": "ဆက်တင်များ", "Settings_ne": "सेटिङ्हरू", "Settings_nl": "Instellingen", "Settings_pl": "Ustawienia", "Settings_ps": "ترتیبات", "Settings_pt": "Configurações", "Settings_ro": "Setări", "Settings_ru": "Настройки", "Settings_si": "සැකසුම්", "Settings_sl": "Nastavitve", "Settings_sv": "Inställningar", "Settings_sw": "Mipangilio", "Settings_ta": "அமைப்புகள்", "Settings_te": "సెట్టింగులు", "Settings_th": "การตั้งค่า", "Settings_tl": "Mga Setting", "Settings_tr": "Ayarlar", "Settings_uk": "Налаштування", "Settings_ur": "ترتیبات", "Settings_vi": "Cài đặt", "Settings_xh": "Izilwande", "Settings_zh": "设置",

  // --- Nav: Logout ---
  "Logout_af": "Teken uit", "Logout_ar": "تسجيل الخروج", "Logout_az": "Çıxış", "Logout_bn": "লগআউট", "Logout_cs": "Odhlásit se", "Logout_de": "Abmelden", "Logout_en": "Logout", "Logout_es": "Cerrar sesión", "Logout_et": "Logi välja", "Logout_fa": "خروج", "Logout_fi": "Kirjaudu ulos", "Logout_fr": "Déconnexion", "Logout_gl": "Pechar sesión", "Logout_gu": "લોગઆઉટ", "Logout_he": "התנתקות", "Logout_hi": "लॉगआउट", "Logout_hr": "Odjava", "Logout_id": "Keluar", "Logout_it": "Disconnetti", "Logout_ja": "ログアウト", "Logout_ka": "გამოსვლა", "Logout_kk": "Шығу", "Logout_km": "ចាកចេញ", "Logout_ko": "로그아웃", "Logout_lt": "Atsijungti", "Logout_lv": "Izrakstīties", "Logout_mk": "Одјава", "Logout_ml": "ലോഗ് ഔട്ട്", "Logout_mn": "Гарах", "Logout_mr": "लॉगआउट", "Logout_my": "ထွက်ရန်", "Logout_ne": "लॉगआउट", "Logout_nl": "Uitloggen", "Logout_pl": "Wyloguj", "Logout_ps": "وتل", "Logout_pt": "Sair", "Logout_ro": "Deconectare", "Logout_ru": "Выйти", "Logout_si": "ඉවත් වන්න", "Logout_sl": "Odjava", "Logout_sv": "Logga ut", "Logout_sw": "Ondoka", "Logout_ta": "வெளியேறு", "Logout_te": "లాగ్ అవుట్", "Logout_th": "ออกจากระบบ", "Logout_tl": "Mag-logout", "Logout_tr": "Çıkış", "Logout_uk": "Вийти", "Logout_ur": "لاگ آؤٹ", "Logout_vi": "Đăng xuất", "Logout_xh": "Phuma", "Logout_zh": "登出",
};

export const getSidebarTranslation = (key: string, lang: string): string => {
  const lookupKey = `${key}_${lang}`;
  return dictionarySidebar[lookupKey] || dictionarySidebar[`${key}_en`] || key;
};