import { Project } from "@/projects/projectTypes";
import { Task } from "@/projects/taskTypes";

export const mockProject: Project = {
  id: "1",
  name: "Website Redesign",
  description:
    "Full overhaul of the marketing website with new brand guidelines and improved UX. The goal is to increase conversion rates by 30% and reduce bounce rate through better information architecture and modern visual design.",
  status: "active",
  priority: "high",
  progress: 68,
  tasksTotal: 24,
  tasksDone: 16,
  tasksInProgress: 5,
  dueDate: "Apr 30, 2025",
  color: "#2b7fff",
  team: [
    { name: "Alice Meier", color: "#2b7fff", initials: "AM" },
    { name: "Bob Keller",  color: "#f04000", initials: "BK" },
    { name: "Clara Sun",   color: "#00c950", initials: "CS" },
    { name: "David Park",  color: "#ad46ff", initials: "DP" },
  ],
};

export const initialTasks: Task[] = [
  {
    id: "t1",
    title: "Audit existing site structure",
    description: "Review all pages and create a sitemap of current state.",
    priority: "high",
    assignee: mockProject.team[0],
    dueDate: "Apr 12",
    tags: ["research"],
    column: "done",
  },
  {
    id: "t2",
    title: "Define new information architecture",
    description: "Map out the new navigation and page hierarchy.",
    priority: "high",
    assignee: mockProject.team[1],
    dueDate: "Apr 14",
    tags: ["planning"],
    column: "done",
  },
  {
    id: "t3",
    title: "Create wireframes for homepage",
    priority: "high",
    assignee: mockProject.team[2],
    dueDate: "Apr 16",
    tags: ["design"],
    column: "done",
  },
  {
    id: "t4",
    title: "Design component library",
    description: "Build reusable UI components in Figma.",
    priority: "medium",
    assignee: mockProject.team[0],
    dueDate: "Apr 18",
    tags: ["design"],
    column: "inprogress",
  },
  {
    id: "t5",
    title: "Implement responsive navigation",
    description: "Mobile-first nav with hamburger menu and mega-menu for desktop.",
    priority: "high",
    assignee: mockProject.team[3],
    dueDate: "Apr 20",
    tags: ["dev"],
    column: "inprogress",
  },
  {
    id: "t6",
    title: "Hero section animation",
    description: "Subtle parallax and fade-in effects for above-the-fold content.",
    priority: "low",
    assignee: mockProject.team[1],
    dueDate: "Apr 22",
    tags: ["dev", "animation"],
    column: "inprogress",
  },
  {
    id: "t7",
    title: "Write copy for About page",
    priority: "medium",
    assignee: mockProject.team[2],
    dueDate: "Apr 19",
    tags: ["content"],
    column: "todo",
  },
  {
    id: "t8",
    title: "SEO metadata audit",
    description: "Review and update all meta titles, descriptions and OG tags.",
    priority: "medium",
    dueDate: "Apr 21",
    tags: ["seo"],
    column: "todo",
  },
  {
    id: "t9",
    title: "Set up analytics tracking",
    priority: "high",
    assignee: mockProject.team[3],
    dueDate: "Apr 23",
    tags: ["dev"],
    column: "todo",
  },
  {
    id: "t10",
    title: "Performance optimisation",
    description: "Achieve Lighthouse score > 90 across all pages.",
    priority: "high",
    assignee: mockProject.team[0],
    dueDate: "Apr 28",
    tags: ["dev"],
    column: "todo",
  },
  {
    id: "t11",
    title: "Accessibility review",
    priority: "medium",
    dueDate: "Apr 29",
    tags: ["qa"],
    column: "todo",
  },
];
